# Generated by Django 3.1.7 on 2021-03-15 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bourbon_name', models.CharField(max_length=50)),
                ('distiller', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=10)),
                ('proof', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('batch_num', models.CharField(max_length=50)),
                ('owned', models.CharField(max_length=50)),
                ('rating', models.CharField(max_length=50)),
                ('notes', models.CharField(max_length=200)),
                ('post_image_url', models.CharField(max_length=200)),
                ('logger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bourbonLogServerAPI.logger')),
            ],
        ),
        migrations.CreateModel(
            name='FlavorSum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor_weight', models.IntegerField()),
                ('flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bourbonLogServerAPI.flavor')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bourbonLogServerAPI.log')),
            ],
        ),
    ]
